DELETE http://localhost:3003/api/blogs/66143af0c0f6a4ec39792afa
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InVzZXIiLCJpZCI6IjY2MTQzYzkwMDdmZGNkOTliMGM5NTYzMiIsImlhdCI6MTcxMjYwMjUxNywiZXhwIjoxNzEyNjA2MTE3fQ.sY00iPmKe3GD7EUd3iBlZaBe4HAmZU7djGBG32SzkPY